name: Deploy PHP Bot

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy PHP Bot
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SSH_HOST}}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          mkdir -p /var/www/bots.lucasbrum.net/
          git clone git@github.com:sistematico/spamsentrybot.git /var/www/bots.lucasbrum.net/spamsentrybot
          cd /var/www/bots.lucasbrum.net/spamsentrybot
          git pull